import 'package:flutter/material.dart';
import '../models/password_entry.dart';
import '../services/password_vault_service.dart';
import '../widgets/password_generator_dialog.dart';
class EditPasswordScreen extends StatefulWidget { final PasswordEntry entry; const EditPasswordScreen({super.key, required this.entry}); @override State<EditPasswordScreen> createState()=>_EditPasswordScreenState(); }
class _EditPasswordScreenState extends State<EditPasswordScreen> { final _form=GlobalKey<FormState>(); late final service=TextEditingController(text:widget.entry.serviceName), username=TextEditingController(text:widget.entry.username), password=TextEditingController(), website=TextEditingController(text:widget.entry.website), notes=TextEditingController(text:widget.entry.notes); late PasswordCategory category=widget.entry.category; late bool favourite=widget.entry.favourite; bool hidden=true, saving=false;
  @override void dispose(){service.dispose();username.dispose();password.dispose();website.dispose();notes.dispose();super.dispose();}
  Future<void> _generate() async { final value=await showDialog<String>(context:context,builder:_=>const PasswordGeneratorDialog()); if(value!=null) password.text=value; }
  Future<void> _save() async { if(!_form.currentState!.validate()) return; setState(()=>saving=true); await PasswordVaultService.instance.update(widget.entry, serviceName: service.text, username: username.text, password: password.text.isEmpty?null:password.text, website: website.text, category: category, notes: notes.text, favourite: favourite); if(mounted) Navigator.pop(context,true); }
  @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('Edit Password')), body:Form(key:_form, child:ListView(padding:const EdgeInsets.all(16), children:[
    TextFormField(controller:service, decoration:const InputDecoration(labelText:'Service Name'), validator:(v)=>v==null||v.trim().isEmpty?'Service Name is required':null), TextFormField(controller:username, decoration:const InputDecoration(labelText:'Username / Email')),
    TextFormField(controller:password, obscureText:hidden, decoration:InputDecoration(labelText:'New Password (leave blank to keep current)', suffixIcon:IconButton(icon:Icon(hidden?Icons.visibility:Icons.visibility_off), onPressed:()=>setState(()=>hidden=!hidden)))), Align(alignment:Alignment.centerRight, child:TextButton.icon(onPressed:_generate, icon:const Icon(Icons.auto_fix_high), label:const Text('Generate Password'))),
    TextFormField(controller:website, decoration:const InputDecoration(labelText:'Website')), DropdownButtonFormField(value:category, decoration:const InputDecoration(labelText:'Category'), items:PasswordCategory.values.map((c)=>DropdownMenuItem(value:c, child:Text(c.label))).toList(), onChanged:(v)=>setState(()=>category=v??PasswordCategory.other)), TextFormField(controller:notes, maxLines:3, decoration:const InputDecoration(labelText:'Notes')), SwitchListTile(value:favourite, onChanged:(v)=>setState(()=>favourite=v), title:const Text('Favourite')), const SizedBox(height:16), FilledButton(onPressed:saving?null:_save, child:Text(saving?'Saving...':'Save')),
  ])));
}
